### PR TITLE
Restore dependencies

### PR DESCRIPTION
**Pull request by m-rossi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Restore the dependencies as proposed in https://github.com/conda-forge/bw2calc-feedstock/pull/14#issuecomment-1689491498

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@cmutel @michaelweinold looking at the source repo I found the following dependencies as `try/except` imports. We may should also add them?

* [`json_logging`](https://github.com/brightway-lca/brightway2-calc/blob/2.0.DEV13/bw2calc/__init__.py#L23)
* [`presamples`](https://github.com/brightway-lca/brightway2-calc/blob/2.0.DEV13/bw2calc/__init__.py#L39)
* [`bw2data`](https://github.com/brightway-lca/brightway2-calc/blob/2.0.DEV13/bw2calc/__init__.py#L43-L44)

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by michaelweinold** [comment]
> @cmutel @michaelweinold looking at the source repo I found the following dependencies as `try/except` imports. We may should also add them?

I would suggest to proceed along my suggestion from yesterday: Make the `dev` label `noarch`, don't provide any LinAlg solvers (and none of the optional packages `json_logging`, `presamples`, `bw2data`). The platform-specific `dev`-label packages we can mark as broken:

- https://github.com/conda-forge/admin-requests/pull/802

@cmutel could create a "2.0.dev14" version of bw2calc that we can add. That would supersede this PR.

On the `main` label, we could add the optional packages to the dependencies explicitly - what do you think, @cmutel?

**Pull request closed without merging**
