### PR TITLE
2.0.dev17 rerender with all OS-specific recipes

### PR DESCRIPTION
**Pull request by cmutel**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cmutel** [comment]
OK, my understanding so far:
- Tests fail on MacOS ARM64 architecture (and 3.8, but this won't work - I will just delete those).
- The error is `Bad CPU type in executable` - smells like an system architecture problem
- The miniforge installation command is `curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-x86_64.sh`
- Isn't that wrong? There is a separate release for [ARM Macs](https://github.com/conda-forge/miniforge/releases/)?

**Comment by m-rossi** [comment]
> - Isn't that wrong? There is a separate release for [ARM Macs](https://github.com/conda-forge/miniforge/releases/)?

~~If I remember correctly~~ Those arm builds are done by cross compilation on _normal_ macOS by default: https://conda-forge.org/docs/maintainer/knowledge_base/#apple-silicon-builds

**Comment by cmutel** [comment]
@m-rossi The recipe linter complains when I pin to `python >3.9`, but conda-smithy wants to generate recipes for 3.8+. I just manually removed all the 3.8 versions, but am happy to be shown a way to do this automatically.

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
> @m-rossi The recipe linter complains when I pin to `python >3.9`, but conda-smithy wants to generate recipes for 3.8+. I just manually removed all the 3.8 versions, but am happy to be shown a way to do this automatically.

Sadly that's a little bit weird. For arch-dependent packages you have to add a `skip: true  # [py<39]` like I already did.

**Comment by cmutel** [comment]
@m-rossi To get this to work on the stable branch we also have the following in `requirements:`

```yaml
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
```

Not sure if this is why, but comparing the build logs of stable and dev, the dependencies installed in `dev` are much shorter.

**Comment by cmutel** [comment]
New packages from stable:

```console
bzip2:                  1.0.8-h0d85af4_4          conda-forge
ca-certificates:        2023.7.22-h8857fd0_0      conda-forge
cctools_osx-64:         973.0.1-ha1c5b94_14       conda-forge
cctools_osx-arm64:      973.0.1-h7bb7a8e_14       conda-forge
libffi:                 3.4.2-h0d85af4_5          conda-forge
libiconv:               1.17-hac89ed1_0           conda-forge
libllvm16:              16.0.6-he4b1e75_2         conda-forge
libsqlite:              3.42.0-h58db7d2_0         conda-forge
libxml2:                2.11.5-hd95e348_0         conda-forge
libzlib:                1.2.13-h8a1eda9_5         conda-forge
llvm-tools:             16.0.6-he4b1e75_2         conda-forge
lz4-c:                  1.9.4-hf0c8a7f_0          conda-forge
ncurses:                6.4-hf0c8a7f_0            conda-forge
openssl:                3.1.2-h8a1eda9_0          conda-forge
popt:                   1.16-h7b079dc_2002        conda-forge
python:                 3.11.4-h30d4d87_0_cpython conda-forge
readline:               8.2-h9e318b2_1            conda-forge
rsync:                  3.2.7-h30d983d_0          conda-forge
sed:                    4.7-h3efe00b_1000         conda-forge
sigtool:                0.1.3-h88f4db0_0          conda-forge
tapi:                   1100.0.11-h9ce4665_0      conda-forge
tk:                     8.6.12-h5dbffcc_0         conda-forge
tzdata:                 2023c-h71feb2d_0          conda-forge
xxhash:                 0.8.0-h35c211d_3          conda-forge
xz:                     5.2.6-h775f41a_0          conda-forge
zstd:                   1.5.2-h829000d_7          conda-forge
```

New packages from dev:

```console
bzip2:           1.0.8-h93a5062_5           conda-forge
ca-certificates: 2024.6.2-hf0a4a13_0        conda-forge
libffi:          3.4.2-h3422bc3_5           conda-forge
libsqlite:       3.45.3-h091b4b1_0          conda-forge
libzlib:         1.3.1-hfb2fe0b_1           conda-forge
ncurses:         6.5-hb89a1cb_0             conda-forge
openssl:         3.3.1-hfb2fe0b_0           conda-forge
pip:             24.0-pyhd8ed1ab_0          conda-forge
python:          3.10.14-h2469fbe_0_cpython conda-forge
readline:        8.2-h92ec313_1             conda-forge
setuptools:      70.0.0-pyhd8ed1ab_0        conda-forge
tk:              8.6.13-h5083fa2_1          conda-forge
tzdata:          2024a-h0c530f3_0           conda-forge
wheel:           0.43.0-pyhd8ed1ab_1        conda-forge
xz:              5.2.6-h57fd34a_0           conda-forge
```

Maybe adding build requirements will help.

**Comment by cmutel** [comment]
@m-rossi Seems like we have the right magical incantations now. Thanks a lot for the support!

**Pull request merged**
