### PR TITLE
Add `dev` build of Package

### PR DESCRIPTION
**Pull request by michaelweinold**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by michaelweinold** [comment]
This would close https://github.com/brightway-lca/brightway-hub/issues/19

**Comment by m-rossi** [comment]
@cmutel & @michaelweinold that was a mistake. You merged into main.

**Comment by michaelweinold** [comment]
Oh, no! I opened the other PRs against the new `dev` branches, but must have incorrectly selected `main` in this case.

**Comment by m-rossi** [comment]
It seems the packages were not pushed to main channel, which is good. We do not need to mark them as broken then.

Let me see if I can fix the repo branches.

**Comment by michaelweinold** [comment]
...for moving stuff to `dev`, we can use: https://github.com/conda-forge/bw2calc-feedstock/pull/12 (or not, according to the conda-forge linting service)

**Pull request merged**
