### PR TITLE
Make the package noarch

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinRenou** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
Are these selectors not a problem for `noarch`? https://github.com/conda-forge/bw2calc-feedstock/blob/main/recipe/meta.yaml#L27-L29

**Comment by michaelweinold** [comment]
> Are these selectors not a problem for `noarch`? https://github.com/conda-forge/bw2calc-feedstock/blob/main/recipe/meta.yaml#L27-L29

Most likely. The `pypardiso` wrapper for the [Intel oneAPI Math Kernel Library PARDISO solver](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/sparse-solver-routines/onemkl-pardiso-parallel-direct-sparse-solver-iface.html) isn't available on non-Intel systems (notably Apple Silicon).

Until recently, this was circumvented by @cmutel providing a [`brightway25_nosolver`](https://anaconda.org/cmutel/brightway25_nosolver) library.

I'd need to check if we can make the package `noarch` and still specify platform-dependent dependencies.

**Comment by martinRenou** [comment]
The selector for `pypardiso` can probably be removed, it's noarch and so available for all platforms. See https://github.com/conda-forge/pypardiso-feedstock/blob/main/recipe/meta.yaml#L15

Concerning `scikit-umfpack`, we may consider packaging it for windows and remove the skip if possible? https://github.com/conda-forge/scikit-umfpack-feedstock/blob/main/recipe/meta.yaml#L14

**Comment by martinRenou** [comment]
> I'd need to check if we can make the package noarch and still specify platform-dependent dependencies.

You can have a package be noarch even though its dependencies are not noarch.

**Comment by michaelweinold** [comment]
> pypardiso can probably be removed, it's noarch and so available for all platforms.

Well, it may be available for all platforms, but the underlying math library is not - correct?

> Concerning scikit-umfpack, we may consider packaging it for windows and remove the skip if possible?

My understanding is that `scikit-umfpack` has sigificantly lower performance than the PARDISO solver on x64 platforms. 

> You can have a package be noarch even though its dependencies are not noarch.

Considering the above, in that case it would probably be best to have `bw2calc` as `noarch`, with platform-specific dependencies:

- pypardiso  # [not (osx and arm64)]
- scikit-umfpack  # [osx and arm64]

**Comment by m-rossi** [comment]
> Until recently, this was circumvented by @cmutel providing a [`brightway25_nosolver`](https://anaconda.org/cmutel/brightway25_nosolver) library.

No, I _fixed_ it with these selectors I introduced in this package during conda-forge-migration, see https://github.com/conda-forge/bw2calc-feedstock/pull/1

To bring another point to the discussion, the recent dev-version can be `noarch` as I proposed in this PR: https://github.com/conda-forge/bw2calc-feedstock/pull/13 May we can just wait until the `bw2calc`-version is released?

**Comment by michaelweinold** [comment]
> No, I _fixed_ it with these selectors I introduced in this package during conda-forge-migration

Yup, I remember - what I was referring to was the olden times, before you added the packages to `conda-forge`. I think that at that time, the only way to circumvent `pypardiso` issues on Apple Silicon was to use the `nosolver` package.

If https://github.com/conda-forge/bw2calc-feedstock/pull/13 solves this, I'll have a look now. Thank you!

**Comment by michaelweinold** [comment]
Closing in favor of https://github.com/conda-forge/bw2calc-feedstock/pull/13

**Comment by cmutel** [comment]
@michaelweinold That was for the `dev` branch, this is for the `main` branch.

**Comment by m-rossi** [comment]
Please wait. We have to slow down a little here.

**Comment by cmutel** [comment]
I merged #13, so that is no longer blocking.

@m-rossi Could provide an explanation or a link on why your PR (#13) needed to remove:

```yaml
 build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
```

But this PR doesn't? Isn't the `target_platform` going to break the `noarch` idea?

**Comment by m-rossi** [comment]
As I explained in https://github.com/conda-forge/bw2calc-feedstock/pull/13#issuecomment-1687848963

> Ok, I think now I am getting what's going wrong here: In https://github.com/conda-forge/bw2calc-feedstock/pull/11 those package providing the sparse solver got removed by @michaelweinold (seems an accident?) and you approved that PR quite quickly. So I guessed those packages are no longer required for bw2calc. But by looking at the code those libraries are still used and the current development version will break.

# Current state
Those dev versions of `bw2calc` are broken as those sparse libaries got remove in https://github.com/conda-forge/bw2calc-feedstock/pull/11

# Proposed solution

~~merge this PR, we just need to define minimal the minimal python version. The selectors based on os are not a problem (am I right @martinRenou?). When this is merged we should bring those changes back to the dev-branch.~~

Minor addition: As the linter points out (https://github.com/conda-forge/bw2calc-feedstock/pull/14#issuecomment-1687790611) selectors are not allowed for noarch.

**Comment by cmutel** [comment]
@m-rossi At this point I am happy to let you take the lead and do whatever is needed. I am more likely to make things worse than better 🤷🏽

**Comment by michaelweinold** [comment]
> [Proposed solution](https://github.com/conda-forge/bw2calc-feedstock/pull/14#issuecomment-1687862680)

I just discussed this with @cmutel. I believe you will find the below useful:

## How the `bw2calc` Library uses Linear Solvers

If neither `pypardiso` or `scikit-umfpack` are installed, it will default to using the `scipy` internal solver. This is solvers has the lowest performance. If `pypardiso` is installed (x64 platforms), it uses that. If `scikit-umfpack` is installed, it uses that.

## Why @michaelweinold removed the Linear Solvers

As I mentioned in my updated comment here https://github.com/conda-forge/bw2calc-feedstock/pull/13#issuecomment-1687854131, I didn't simply forget to include the `pypardiso`/`scikit-umfpack` libraries in the initial PR. I used the packages listed in `setup.py` of `bw2calc`. This was a mistake - while (as mentioned above) the package would default to `scipy` if no solvers are provided, the `main` label of this package on conda-forge should continue to offer selectors with platform-specific solvers.

## Our Suggestion

> [!IMPORTANT]
> We use the conda-forge __label__ functionality to release a `noarch` version of the package specifically for the purpose of WASM development. This will allow us to close:

- https://github.com/brightway-lca/brightway-hub/issues/23

Precedence: The Anaconda Cloud team [suggests the use of custom labels](https://docs.anaconda.com/free/anacondaorg/user-guide/tutorials/#using-labels-in-the-development-cycle). In addition, a large number of package use the label funtionality outside of the two use-cases `dev` and `rc`, which are explicitly mentioned in [CFEP-05](https://github.com/conda-forge/cfep/blob/main/cfep-05.md).

## Next Steps

1. This PR (`main` label) should use selectors and will not be `noarch`.
2. [Mark the latest `dev` version as broken](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages) (cf. [my fork of the admin-requests repo](https://github.com/michaelweinold/admin-requests)).
3. Create a new label `wasm` that does not include any solvers (and no selectors). This would be `noarch`.

Let us know what you think, @m-rossi. Thanks!

**Comment by martinRenou** [comment]
> 3. Create a new label wasm that does not include any solvers (and no selectors). This would be noarch.

Alternatively, you could also push a recipe for bw2calc on emscripten-forge https://github.com/emscripten-forge/recipes. Up to you to decide what you prefer to do.

**Comment by michaelweinold** [comment]
@m-rossi, please let me know if you have any objections. I will then draft the PR for the new `wasm` label.

**Comment by m-rossi** [comment]
> @m-rossi, please let me know if you have any objections. I will then draft the PR for the new `wasm` label.

Sorry for the late reply @michaelweinold, today and yesterday is/was a really busy workday. 

> ## Our Suggestion
> 
> Important We use the conda-forge **label** functionality to release a `noarch` version of the package specifically for the purpose of WASM development. This will allow us to close:
> 
>     * [JupyterLite Micromamba can't find Brightway Packages (under `dev` Label) brightway-lca/brightway-hub#23](https://github.com/brightway-lca/brightway-hub/issues/23)
> 
> 
> Precedence: The Anaconda Cloud team [suggests the use of custom labels](https://docs.anaconda.com/free/anacondaorg/user-guide/tutorials/#using-labels-in-the-development-cycle). In addition, a large number of package use the label funtionality outside of the two use-cases `dev` and `rc`, which are explicitly mentioned in [CFEP-05](https://github.com/conda-forge/cfep/blob/main/cfep-05.md).

I am not sure if we can make use of custom labels using the _standards_ of conda-forge. The CFEP you mention is about those pre-release stuff.

Therefore I suggest:
1. Add the recipe to https://github.com/emscripten-forge/recipes as the noarch is only useful for jupyterlite/wasm-usage. When we sorted [these issues](https://github.com/conda-forge/bw2calc-feedstock/pull/14#issuecomment-1687809543) we can make this package also noarch.
2. Re-add the solvers back to the dev-packages (I will take care of this in #15).

**Comment by michaelweinold** [comment]
> [Therefore I suggest](https://github.com/conda-forge/bw2calc-feedstock/pull/14#issuecomment-1689491498)

I'm happy with your suggestions. I will proceed to add a `noarch` version with no specific solver dependencies of `bw2calc` to `emscipten-forge`. Thank you for the feedback!

 - [ ] https://github.com/emscripten-forge/recipes/pull/616

**Comment by m-rossi** [comment]
Ok, I will close this PR then.

**Pull request closed without merging**
